sonar.projectKey=JC-Software-Solution_userinfo-service
sonar.organization=jc-software-solution
sonar.host.url=https://sonarcloud.io

# Source code directory
sonar.sources=src/main

# Tests directory
sonar.tests=src/test

# Coverage settings
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

