name: unit_test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Run tests with coverage
        run: mvn clean test verify -Pcodecoverage

      - name: Print code coverage
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet
          
          FILE=target/site/jacoco/jacoco.xml
          
          LINE_COVERED=$(xmllint --xpath "string(//counter[@type='LINE']/@covered)" $FILE)
          LINE_MISSED=$(xmllint --xpath "string(//counter[@type='LINE']/@missed)" $FILE)
          
          TOTAL=$((LINE_COVERED + LINE_MISSED))
          COVERAGE=$(awk "BEGIN {printf \"%.2f\", ($LINE_COVERED/$TOTAL)*100}")
          
          echo "=========================="
          echo "LINE COVERAGE: $COVERAGE%"
          echo "=========================="

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/